import React, { useState } from "react";
import { Loader2 } from "lucide-react";
import { useLocation } from "wouter";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { usePageMeta } from "@/hooks/usePageMeta";

const countries = [{ label: "Liberia (+231)", code: "+231" }, { label: "Ghana (+233)", code: "+233" }, { label: "Nigeria (+234)", code: "+234" }, { label: "United States (+1)", code: "+1" }, { label: "United Kingdom (+44)", code: "+44" }, { label: "Other international", code: "+" }];

export default function Auth() {
  usePageMeta("Sign in", "Sign in or create a BeatBox account to license tracks, save favorites, and sell your beats.");
  const { signIn, signUp, signInWithGoogle, resetPassword, signInWithPhone, verifyPhoneOtp, user } = useSupabaseAuth();
  const [, setLocation] = useLocation();
  const [mode, setMode] = useState<"signin" | "signup" | "reset" | "phone">("signin");
  const [name, setName] = useState(""); const [email, setEmail] = useState(""); const [password, setPassword] = useState(""); const [country, setCountry] = useState("+231"); const [phone, setPhone] = useState(""); const [otp, setOtp] = useState(""); const [otpSent, setOtpSent] = useState(false); const [message, setMessage] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  if (user) { setLocation("/account"); return null; }
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setBusy(true); setMessage(null); try { if (mode === "phone") { const normalized = `${country}${phone.replace(/\D/g, "")}`; if (!otpSent) { await signInWithPhone(normalized); setOtpSent(true); setMessage("A verification code was requested. If SMS auth is enabled for this Supabase project, enter it below."); } else { await verifyPhoneOtp(normalized, otp); setLocation("/account"); } } else if (mode === "signin") { await signIn(email, password); setLocation("/account"); } else if (mode === "signup") { await signUp(name, email, password); setMessage("Check your email to confirm your BeatBox account, then return to sign in."); } else { await resetPassword(email); setMessage("Password reset instructions were sent if that email is registered."); } } catch (error) { setMessage(error instanceof Error ? error.message : "Unable to continue. Check the configured authentication providers and try again."); } finally { setBusy(false); } };
  const label = mode === "signin" ? "Welcome back" : mode === "signup" ? "Make more room for your sound" : mode === "phone" ? "Sign in with phone" : "Reset your password";
  return <section className="auth-page"><div className="auth-card"><p className="eyebrow"><span /> BeatBox account</p><h1>{label}</h1><p className="auth-card__lede">{mode === "signin" ? "Access your collection, requests, and secure downloads." : mode === "signup" ? "Create a free buyer account. You can become a seller at any time—no approval queue." : mode === "phone" ? "Use an international phone number. SMS OTP requires phone auth to be enabled in Supabase." : "We’ll email a secure reset link."}</p>{mode !== "phone" && <button className="oauth-button" type="button" onClick={() => void signInWithGoogle()} disabled={busy}><span>G</span> Continue with Google</button>}{mode !== "phone" && <div className="auth-divider"><span>or use email</span></div>}<form onSubmit={submit}>{mode === "signup" && <label>Display name<input value={name} onChange={event => setName(event.target.value)} required minLength={2} /></label>}{mode === "phone" ? <><label>Country<select value={country} onChange={event => setCountry(event.target.value)}>{countries.map(item => <option key={item.code} value={item.code}>{item.label}</option>)}</select></label><label>Phone number<input type="tel" value={phone} onChange={event => setPhone(event.target.value)} required placeholder="770123456" autoComplete="tel" /></label>{otpSent && <label>Verification code<input inputMode="numeric" value={otp} onChange={event => setOtp(event.target.value)} required minLength={6} maxLength={8} autoComplete="one-time-code" /></label>}</> : <><label>Email<input type="email" value={email} onChange={event => setEmail(event.target.value)} required autoComplete="email" /></label>{mode !== "reset" && <label>Password<input type="password" value={password} onChange={event => setPassword(event.target.value)} required minLength={8} autoComplete={mode === "signin" ? "current-password" : "new-password"} /></label>}</>}<button className="button auth-card__submit" disabled={busy} type="submit">{busy && <Loader2 className="spin" size={16} />}{mode === "signin" ? "Sign in" : mode === "signup" ? "Create account" : mode === "phone" ? otpSent ? "Verify code" : "Send code" : "Send reset link"}</button></form>{message && <p className={message.startsWith("Check") || message.startsWith("Password") || message.startsWith("A verification") ? "form-success" : "form-error"} role="status">{message}</p>}<div className="auth-card__links"><button type="button" onClick={() => { setMode("signin"); setOtpSent(false); }}>{mode !== "signin" ? "Already have an account? Sign in" : ""}</button><button type="button" onClick={() => { setMode("signup"); setOtpSent(false); }}>New to BeatBox? Create an account</button><button type="button" onClick={() => { setMode("phone"); setOtpSent(false); }}>Use phone OTP</button><button type="button" onClick={() => setMode("reset")}>Forgot password?</button></div></div></section>;
}
