import { PaymentRequestPanel } from "@/components/PaymentRequestPanel";
import { useSupabaseAuth } from "@/contexts/SupabaseAuthContext";
import { usePageMeta } from "@/hooks/usePageMeta";
import { money, toDisplayBeat } from "@/lib/marketplace";
import type { Beat } from "@/lib/models";
import { supabase } from "@/lib/supabase";
import { Loader2, ShoppingBag, Trash2 } from "lucide-react";
import { useEffect, useState } from "react";
import { Link } from "wouter";
type CartItem = { id: string; beat_id: string; license_id: string | null; beats: Beat | null };
export default function Cart() { const { user } = useSupabaseAuth(); usePageMeta("Your cart", "Review the beats you plan to license on BeatBox."); const [items,setItems]=useState<CartItem[]>([]); const [loading,setLoading]=useState(true); const [open,setOpen]=useState<string|null>(null); const load=async()=>{if(!user){setLoading(false);return;}setLoading(true);const{data,error}=await supabase.from("cart_items").select("id, beat_id, license_id, beats(*)").eq("user_id",user.id).order("created_at",{ascending:false});if(error){setItems([]);}else{setItems(await Promise.all((data??[]).map(async item=>{const nested = Array.isArray(item.beats) ? item.beats[0] : item.beats; return {...item,beats:nested?await toDisplayBeat(nested as Beat):null};})) as CartItem[]);}setLoading(false);};useEffect(()=>{void load();},[user?.id]);const remove=async(id:string)=>{await supabase.from("cart_items").delete().eq("id",id);void load();};if(!user)return <section className="status-page"><ShoppingBag size={34}/><h1>Your cart is waiting.</h1><p>Sign in to save and request licenses for your beats.</p><Link className="button" href="/auth">Sign in</Link></section>;return <section className="cart-page"><div className="container"><p className="eyebrow"><span/> Your collection</p><h1>Cart &amp; checkout</h1><p className="cart-page__lede">BeatBox sends payment requests to producers. A master is never released until payment is verified by the appropriate seller or an administrator.</p>{loading?<div className="status-inline"><Loader2 className="spin"/>Loading cart…</div>:items.length?<div className="cart-list">{items.map(item=>item.beats&&<article className="cart-row" key={item.id}><div className="cart-row__cover">{item.beats.cover_url?<img src={item.beats.cover_url} alt=""/>:<span>BB</span>}</div><div><Link href={`/beats/${item.beats.slug}`}><h2>{item.beats.title}</h2></Link><p>{item.beats.producer||"BeatBox producer"} · {item.beats.genre||"Original"}</p></div><strong>{item.beats.is_free?"Free":money(item.beats.price)}</strong><button className="icon-action" onClick={()=>void remove(item.id)} aria-label="Remove from cart"><Trash2 size={16}/></button><button className="button button--small" onClick={()=>setOpen(open===item.id?null:item.id)}>Request payment</button>{open===item.id&&!item.beats.is_free&&<div className="cart-row__payment"><PaymentRequestPanel beat={item.beats}/></div>}</article>)}</div>:<div className="empty-featured empty-featured--light"><ShoppingBag size={34}/><h2>Your cart is empty.</h2><p>Find a beat you love, then add it here before you request payment.</p><Link className="button" href="/explore">Browse beats</Link></div>}</div></section>;}
