import { Heart, Loader2, Reply, Send, ShieldAlert, Trash2 } from "lucide-react";
import React, { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";

type Comment = { id: string; post_id: string; user_id: string; parent_id: string | null; body: string; like_count: number; created_at: string; profiles?: { display_name: string | null; username: string | null } | null };

function renderBody(body: string) {
  return body.split(/(#[a-zA-Z0-9_]+|@[a-zA-Z0-9_]+)/g).map((part, index) => part.startsWith("#") || part.startsWith("@") ? <a key={index} href={part.startsWith("#") ? `/search?q=${encodeURIComponent(part.slice(1))}&type=hashtag` : `/creators/${encodeURIComponent(part.slice(1))}`} className="inline-token">{part}</a> : <span key={index}>{part}</span>);
}

export function CommentThread({ postId, userId, onCountChange }: { postId: string; userId?: string; onCountChange?: (delta: number) => void }) {
  const [comments, setComments] = useState<Comment[]>([]);
  const [body, setBody] = useState("");
  const [replyTo, setReplyTo] = useState<string | null>(null);
  const [liked, setLiked] = useState<Record<string, boolean>>({});
  const [loading, setLoading] = useState(true);
  const [message, setMessage] = useState<string | null>(null);
  const load = async () => { setLoading(true); const result = await supabase.from("social_post_comments").select("id,post_id,user_id,parent_id,body,like_count,created_at,profiles(display_name,username)").eq("post_id", postId).order("created_at", { ascending: true }); if (!result.error) setComments((result.data || []).map(row => ({ ...row, profiles: Array.isArray(row.profiles) ? row.profiles[0] || null : row.profiles || null })) as Comment[]); if (userId) { const likes = await supabase.from("social_post_comment_likes").select("comment_id").eq("user_id", userId); if (!likes.error) setLiked(Object.fromEntries((likes.data || []).map(row => [row.comment_id, true]))); } setLoading(false); };
  useEffect(() => { void load(); }, [postId, userId]);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); if (!userId) { setMessage("Sign in to comment."); return; } const text = body.trim(); if (!text) return; const result = await supabase.from("social_post_comments").insert({ post_id: postId, user_id: userId, parent_id: replyTo, body: text }); if (result.error) setMessage(result.error.message); else { setMessage("Comment added."); setBody(""); setReplyTo(null); onCountChange?.(1); void load(); } };
  const toggleLike = async (comment: Comment) => { if (!userId) { setMessage("Sign in to like comments."); return; } const active = Boolean(liked[comment.id]); const result = active ? await supabase.from("social_post_comment_likes").delete().eq("comment_id", comment.id).eq("user_id", userId) : await supabase.from("social_post_comment_likes").insert({ comment_id: comment.id, user_id: userId }); if (!result.error) { setLiked(current => ({ ...current, [comment.id]: !active })); setComments(current => current.map(item => item.id === comment.id ? { ...item, like_count: Math.max(0, item.like_count + (active ? -1 : 1)) } : item)); } };
  const remove = async (comment: Comment) => { const result = await supabase.from("social_post_comments").delete().eq("id", comment.id).eq("user_id", userId || ""); if (!result.error) { setComments(current => current.filter(item => item.id !== comment.id)); onCountChange?.(-1); } else setMessage(result.error.message); };
  const report = async (comment: Comment) => { if (!userId) { setMessage("Sign in to report comments."); return; } const result = await supabase.from("reports").insert({ reporter_id: userId, reported_post_id: postId, reason: "comment", description: comment.body.slice(0, 500) }); setMessage(result.error ? result.error.message : "Comment report submitted."); };
  return <section className="comment-thread" aria-label="Comments"><form className="comment-thread__composer" onSubmit={submit}><textarea aria-label="Write a comment" rows={2} value={body} onChange={event => setBody(event.target.value)} placeholder={replyTo ? "Write a reply…" : "Add a thoughtful comment…"} /><button className="button button--small" type="submit" disabled={!body.trim()}><Send size={14} /> Post</button></form>{replyTo && <button type="button" className="text-button" onClick={() => setReplyTo(null)}>Cancel reply</button>}{message && <small className="form-success" role="status">{message}</small>}{loading ? <Loader2 className="spin" size={18} /> : comments.length ? <div className="comment-thread__list">{comments.map(comment => <article className={`comment ${comment.parent_id ? "comment--reply" : ""}`} key={comment.id}><div className="comment__meta"><b>{comment.profiles?.display_name || comment.profiles?.username || "BeatBox member"}</b><time dateTime={comment.created_at}>{new Date(comment.created_at).toLocaleString()}</time></div><p>{renderBody(comment.body)}</p><div className="comment__actions"><button type="button" onClick={() => void toggleLike(comment)} className={liked[comment.id] ? "is-active" : ""}><Heart size={14} /> {comment.like_count}</button><button type="button" onClick={() => setReplyTo(comment.id)}><Reply size={14} /> Reply</button>{comment.user_id === userId && <button type="button" onClick={() => void remove(comment)} aria-label="Delete your comment"><Trash2 size={14} /></button>}<button type="button" onClick={() => void report(comment)} aria-label="Report comment"><ShieldAlert size={14} /></button></div></article>)}</div> : <p className="muted-copy">No comments yet. Start the conversation.</p>}</section>;
}
